version: "3"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
  db:
    image: mariadb:latest
    restart: always
    container_name: db
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql/init.sql:/data/init.sql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    networks:
      - default
  web:
    image: nginx:latest
    restart: always
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '127.0.0.1:80:80'
    depends_on:
      - php
  php:
    build: './php'
    container_name: laravel.local
    volumes:
      - ../:/var/www/html
    ports:
      - '127.0.0.1:9001:9000'
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
  mail:
    image: 'mailhog/mailhog'
    restart: always
    container_name: mailhog
    ports:
      - '127.0.0.1:1025:1025'
      - '127.0.0.1:8025:8025'
    networks:
      - default
  chrome:
    image: selenium/node-chrome:4.1.2-20220217
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - default
  selenium-hub:
    image: selenium/hub:4.1.2-20220217
    container_name: selenium-hub
    ports:
      - "127.0.0.1:4442:4442"
      - "127.0.0.1:4443:4443"
      - "127.0.0.1:4444:4444"
    networks:
      - default
volumes:
  db-data:
    driver: local
networks:
  default:
